### ISSUE TITLE
How to use this project？

### ISSUE THREAD

**Issue by xbotao** [JoseRodriguezRomero/LCAM-PES#1]
Hi,

I down your project and run. There are some errors in `visa_resouce.h`.
```
cannot find the head file <visa.h>
```

What should I do?

**Comment by JoseRodriguezRomero** [comment]
Are you trying to compile it on Windows or Linux? In the case of Windows you need to install the visa driver form either national instruments or from keysight. Installing the visa drivers from national instruments in Linux is possible, but definitely trickier, if that is the case I can write you down a step by step solution if you need one.

Once installed you need to put the required dll paths in the project configuration file. I have done some changes in the project but I forgot to pull those changes here (I'll do that in a minute)

**Comment by xbotao** [comment]
Thanks!
I try to  compile it on **Windows 10** and **Qt 5.80**. I will install visa driver and try agian.

**Comment by JoseRodriguezRomero** [comment]
Beware that in the LCAM1.pro file instead of visa32.lib you might instead need something like visa64.lib if you are running a 64 bit system, and wish to compile a 64 bit executable.

**Comment by xbotao** [comment]
I complie with visa32. It works!
